linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
    settings: # settings passed to gocritic
      rangeValCopy:
        sizeThreshold: 500
      hugeParam:
        sizeThreshold: 500
  gocyclo:
    min-complexity: 30
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  golint:
    min-confidence: 25
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: return
  govet:
    check-shadowing: true

  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  # don't enable:
  # - gochecknoglobals
  # - gocognit
  # - godox
  # - maligned
  # - prealloc

  # - funlen
  # - gochecknoinits

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
        - gomnd
        - errcheck
        - goconst
        - dupl

    - linters:
        - staticcheck
      text: "SA9004:"

    - linters:
        - stylecheck
      text: "ST1003:"
    - linters:
        - stylecheck
      text: "ST1005:"

  exclude:
    - composite

run:
  modules-download-mode: readonly

  skip-dirs:
    - pkg/adapters/tessitura/pkg/gotess
